### ISSUE TITLE
Consider fallback of 'Recent Projects' for noscript users

### ISSUE THREAD

**Issue by half-cambodian-hacker-man** [Scetch/blucier.com#1]
If you put some content in the div, like "It seems like there was an issue fetching recent projects, why not [take a look at my GitHub?](//github.com/Scetch/)"; and clear it with JS, this would mean that people who have JavaScript disabled or people without connectivity to GitHub's API would not see a header proceeded by a blank section.

**Comment by Scetch** [comment]
Good suggestion.
